add shclog
go-slog/awesome-slog pull request #22
Opened 2024-03-16 20:35 UTC by ValerySidorin

2024-03-17 00:47 UTC, sagikazarmark approved these changes
Thanks!

2024-03-17 00:48 UTC, sagikazarmark requested changes
On second look: this should probably go under the integrations section since it integrates slog into hclog and not the other way around.

2024-03-17 06:57 UTC, ValerySidorin commented
> On second look: this should probably go under the integrations section since it integrates slog into hclog and not the other way around.

Done!

2024-04-13 22:03 UTC, sagikazarmark approved these changes

2024-04-13 22:04 UTC, merged